## [참조](https://tutorials.pytorch.kr/beginner/pytorch_with_examples.html)
## [해석참고](https://pbj0812.tistory.com/137)
 - 머리속으로 그려보며 가공되는 텐서들의 그림을 그려보며 1cycle을 짤 수 있어야 함

In [1]:
# Numpy 복습
a = np.array([1, 2, 3])
b = np.array([2, 3, 4])

print('numpy.dot(a,b) : ', np.dot(a,b))

numpy.dot(a,b) :  20


In [24]:
c = np.arange(6).reshape(3, 2)
d = np.arange(6).reshape(2, 3)

print('c\n', c)
print('d\n', d)
print('numpy.dot(c, d)')
print(np.dot(c, d))
print()
print('numpy.dot(c, d).shape :')
print(np.dot(c, d).shape)

c
 [[0 1]
 [2 3]
 [4 5]]
d
 [[0 1 2]
 [3 4 5]]
numpy.dot(c, d)
[[ 3  4  5]
 [ 9 14 19]
 [15 24 33]]

numpy.dot(c, d).shape :
(3, 3)


In [6]:
import numpy as np

d1 = np.random.rand(2, 6) # 0~1사이의 표준정규분포 난수를 matrix array(m, n) 생성
w1 = np.random.randn(6, 2) # 평균0, 표준편차1의 가우시안 표준정규분포 난수를 matrix array(m,n) 생성

w1
#d1.dot(w1)

array([[-0.76327884, -0.47706742],
       [ 1.07968177, -1.01061285],
       [ 0.05184889, -0.02901645],
       [ 1.07202986,  1.06132859],
       [ 0.64864974,  1.01017646],
       [-0.32026815,  2.27840162]])

In [8]:
import torch
x = torch.empty(5, 3)
print(x)

tensor([[8.3959e-33, 1.3563e-19, 1.3563e-19],
        [1.0899e+27, 4.5828e+30, 1.0302e+21],
        [4.5630e+30, 8.9064e-15, 1.1578e+27],
        [3.3876e-12, 7.6197e+31, 2.7490e+20],
        [1.5769e-19, 7.5747e+23, 1.7754e+28]])


In [9]:
y = torch.LongTensor([1])
print(y)

tensor([1])


In [2]:
# Numpy 확인
import numpy as np

# N은 배치 크기이며, D_in은 입력의 차원입니다;
# H는 은닉층의 차원이며, D_out은 출력 차원입니다.
N, D_in, H, D_out = 64, 1000, 100, 10

# 무작위의 입력과 출력 데이터를 생성합니다.
x = np.random.randn(N, D_in) # 평균0, 표준편차1의 가우시안 표준정규분포 난수를 matrix array로 생성
y = np.random.randn(N, D_out)

# 무작위로 가중치를 초기화합니다.
w1 = np.random.randn(D_in, H) 
w2 = np.random.randn(H, D_out)

learning_rate = 1e-6

for t in range(500):
    # 순전파 단계: 예측값 y를 계산합니다.
    h = x.dot(w1) # x와 w1 곱셈. # x(input값)와 w1(가중치)를 곱함
    h_relu = np.maximum(h, 0) # https://stackoverflow.com/questions/33569668/numpy-max-vs-amax-vs-maximum
    y_pred = h_relu.dot(w2) # relu은닉층을 거쳐서 나온 값과 w2(가중치)를 곱하여 예측값 추출

    # 손실(loss)을 계산하고 확인합니다.
    loss = np.square(y_pred - y).sum()
    print(t, loss)
    
    # 손실에 따른 w1, w2의 변화도를 계산하고 역전파합니다.
    grad_y_pred = 2.0 * (y_pred - y)
    grad_w2 = h_relu.T.dot(grad_y_pred)
    grad_h_relu = grad_y_pred.dot(w2.T)
    grad_h = grad_h_relu.copy()
    grad_h[h < 0] = 0
    grad_w1 = x.T.dot(grad_h)

    # 가중치를 갱신합니다.
    w1 -= learning_rate * grad_w1
    w2 -= learning_rate * grad_w2

   

0 32492087.973676823
1 32492087.973676823
2 32492087.973676823
3 32492087.973676823
4 32492087.973676823
5 32492087.973676823
6 32492087.973676823
7 32492087.973676823
8 32492087.973676823
9 32492087.973676823
10 32492087.973676823
11 32492087.973676823
12 32492087.973676823
13 32492087.973676823
14 32492087.973676823
15 32492087.973676823
16 32492087.973676823
17 32492087.973676823
18 32492087.973676823
19 32492087.973676823
20 32492087.973676823
21 32492087.973676823
22 32492087.973676823
23 32492087.973676823
24 32492087.973676823
25 32492087.973676823
26 32492087.973676823
27 32492087.973676823
28 32492087.973676823
29 32492087.973676823
30 32492087.973676823
31 32492087.973676823
32 32492087.973676823
33 32492087.973676823
34 32492087.973676823
35 32492087.973676823
36 32492087.973676823
37 32492087.973676823
38 32492087.973676823
39 32492087.973676823
40 32492087.973676823
41 32492087.973676823
42 32492087.973676823
43 32492087.973676823
44 32492087.973676823
45 32492087.97367682

385 32492087.973676823
386 32492087.973676823
387 32492087.973676823
388 32492087.973676823
389 32492087.973676823
390 32492087.973676823
391 32492087.973676823
392 32492087.973676823
393 32492087.973676823
394 32492087.973676823
395 32492087.973676823
396 32492087.973676823
397 32492087.973676823
398 32492087.973676823
399 32492087.973676823
400 32492087.973676823
401 32492087.973676823
402 32492087.973676823
403 32492087.973676823
404 32492087.973676823
405 32492087.973676823
406 32492087.973676823
407 32492087.973676823
408 32492087.973676823
409 32492087.973676823
410 32492087.973676823
411 32492087.973676823
412 32492087.973676823
413 32492087.973676823
414 32492087.973676823
415 32492087.973676823
416 32492087.973676823
417 32492087.973676823
418 32492087.973676823
419 32492087.973676823
420 32492087.973676823
421 32492087.973676823
422 32492087.973676823
423 32492087.973676823
424 32492087.973676823
425 32492087.973676823
426 32492087.973676823
427 32492087.973676823
428 3249208

In [4]:
# PyTorch: Tensors
# Tensors = Numpy array (동일)
import torch

dtype = torch.float
device = torch.device("cpu")
# device = torch.device("cuda:0") # GPU에서 실행하려면 이 주석을 제거하세요.

# N은 배치 크기이며, D_in은 입력의 차원입니다;
# H는 은닉층의 차원이며, D_out은 출력 차원입니다.
N, D_in, H, D_out = 64, 1000, 100, 10

# 입력과 출력을 저장하기 위해 무작위 값을 갖는 Tensor를 생성합니다.
x = torch.randn(N, D_in, device=device, dtype=dtype)
y = torch.randn(N, D_out, device=device, dtype=dtype)

# 가중치를 저장하기 위해 무작위 값을 갖는 Tensor를 생성합니다.
w1 = torch.randn(D_in, H, device=device, dtype=dtype)
w2 = torch.randn(H, D_out, device=device, dtype=dtype)

learning_rate = 1e-6
for t in range(500):
    # 순전파 단계: 예측값 y를 계산합니다.
    h = x.mm(w1)  # matmul하여 h layer 생성
    h_relu = h.clamp(min=0) # ReLU : 0보다 작은 입력값은 0으로 만드는 함수. 필요없는 가중치를 지워버린다
    y_pred = h_relu.mm(w2)

    # 손실(loss)을 계산하고 출력합니다.
    loss = (y_pred - y).pow(2).sum().item()   # loss변수 다음 예제에서 사용됨
    if t % 100 == 99:
        print(t, loss)

    # 손실에 따른 w1, w2의 변화도를 계산하고 역전파합니다.
    grad_y_pred = 2.0 * (y_pred - y)
    grad_w2 = h_relu.t().mm(grad_y_pred)
    grad_h_relu = grad_y_pred.mm(w2.t())
    grad_h = grad_h_relu.clone()
    grad_h[h < 0] = 0
    grad_w1 = x.t().mm(grad_h)

    # 경사하강법(gradient descent)를 사용하여 가중치를 갱신합니다.
    w1 -= learning_rate * grad_w1
    w2 -= learning_rate * grad_w2

tensor(34089088.)
tensor(34089088.)
tensor(34089088.)
tensor(34089088.)
tensor(34089088.)
tensor(34089088.)
tensor(34089088.)
tensor(34089088.)
tensor(34089088.)
tensor(34089088.)
tensor(34089088.)
tensor(34089088.)
tensor(34089088.)
tensor(34089088.)
tensor(34089088.)
tensor(34089088.)
tensor(34089088.)
tensor(34089088.)
tensor(34089088.)
tensor(34089088.)
tensor(34089088.)
tensor(34089088.)
tensor(34089088.)
tensor(34089088.)
tensor(34089088.)
tensor(34089088.)
tensor(34089088.)
tensor(34089088.)
tensor(34089088.)
tensor(34089088.)
tensor(34089088.)
tensor(34089088.)
tensor(34089088.)
tensor(34089088.)
tensor(34089088.)
tensor(34089088.)
tensor(34089088.)
tensor(34089088.)
tensor(34089088.)
tensor(34089088.)
tensor(34089088.)
tensor(34089088.)
tensor(34089088.)
tensor(34089088.)
tensor(34089088.)
tensor(34089088.)
tensor(34089088.)
tensor(34089088.)
tensor(34089088.)
tensor(34089088.)
tensor(34089088.)
tensor(34089088.)
tensor(34089088.)
tensor(34089088.)
tensor(34089088.)
tensor(340

In [4]:
#Pytorch : autograd

import torch

dtype = torch.float
device = torch.device("cpu")
# device = torch.device("cuda:0") # GPU에서 실행하려면 이 주석을 제거하세요.

# N은 배치 크기이며, D_in은 입력의 차원입니다;
# H는 은닉층의 차원이며, D_out은 출력 차원입니다.
N, D_in, H, D_out = 64, 1000, 100, 10

# 입력과 출력을 저장하기 위해 무작위 값을 갖는 Tensor를 생성합니다.
# requires_grad=False로 설정하여 역전파 중에 이 Tensor들에 대한 변화도를 계산할
# 필요가 없음을 나타냅니다. (requres_grad의 기본값이 False이므로 아래 코드에는
# 이를 반영하지 않았습니다.)
x = torch.randn(N, D_in, device=device, dtype=dtype)
y = torch.randn(N, D_out, device=device, dtype=dtype)

# 가중치를 저장하기 위해 무작위 값을 갖는 Tensor를 생성합니다.
# requires_grad=True로 설정하여 역전파 중에 이 Tensor들에 대한
# 변화도를 계산할 필요가 있음을 나타냅니다.
w1 = torch.randn(D_in, H, device=device, dtype=dtype, requires_grad=True) ## 파라미터 추적
w2 = torch.randn(H, D_out, device=device, dtype=dtype, requires_grad=True) ## 파라미터 추적

learning_rate = 1e-6
since = time.time()
for t in range(500):
    # 순전파 단계: Tensor 연산을 사용하여 예상되는 y 값을 계산합니다. 이는 Tensor를
    # 사용한 순전파 단계와 완전히 동일하지만, 역전파 단계를 별도로 구현하지 않아도
    # 되므로 중간값들에 대한 참조(reference)를 갖고 있을 필요가 없습니다. (변수 하나로 처리)
    y_pred = x.mm(w1).clamp(min=0).mm(w2)

    # Tensor 연산을 사용하여 손실을 계산하고 출력합니다.
    # loss는 (1,) 형태의 Tensor이며, loss.item()은 loss의 스칼라 값입니다.
    loss = (y_pred - y).pow(2).sum() # item() 생략
    if t % 100 == 99:
        print(t, loss.item())

    # autograd를 사용하여 역전파 단계를 계산합니다. 이는 requires_grad=True를
    # 갖는 모든 Tensor에 대해 손실의 변화도를 계산합니다. 이후 w1.grad와 w2.grad는
    # w1과 w2 각각에 대한 손실의 변화도를 갖는 Tensor가 됩니다.
    loss.backward()  # loss들만 알면 계산식 없이 알아서 해주네...

    # 경사하강법(gradient descent)을 사용하여 가중치를 수동으로 갱신합니다.
    # torch.no_grad()로 감싸는 이유는 가중치들이 requires_grad=True이지만
    # autograd에서는 이를 추적할 필요가 없기 때문입니다.
    # 다른 방법은 weight.data 및 weight.grad.data를 조작하는 방법입니다.
    # tensor.data가 tensor의 저장공간을 공유하기는 하지만, 이력을
    # 추적하지 않는다는 것을 기억하십시오.
    # 또한, 이를 위해 torch.optim.SGD 를 사용할 수도 있습니다.
    with torch.no_grad():
        w1 -= learning_rate * w1.grad
        w2 -= learning_rate * w2.grad

        # 가중치 갱신 후에는 수동으로 변화도를 0으로 만듭니다.
        w1.grad.zero_()
        w2.grad.zero_()

now = time.time()
print(now - since)

NameError: name 'time' is not defined

## autograd 함수화

In [3]:
import torch


class MyReLU(torch.autograd.Function):
    """
    pytorch에 내장된 
    torch.autograd.Function을 상속받아 사용자 정의 autograd Function을 구현하고,
    Tensor 연산을 하는 순전파와 역전파 단계를 구현하겠습니다.
    """

    @staticmethod  # 함수 재정의
    def forward(ctx, input):  # input : x.mm(w1)
        """
        순전파 단계에서는 입력을 갖는 Tensor를 받아 출력을 갖는 Tensor를 반환합니다.
        ctx는 컨텍스트 객체(context object)로 역전파 연산을 위한 정보 저장에
        사용합니다. ctx.save_for_backward method를 사용하여 역전파 단계에서 사용할 어떠한
        객체도 저장(cache)해 둘 수 있습니다.
        """
        ctx.save_for_backward(input)
        return input.clamp(min=0)  # return : x.mm(w1).clamp(min=0)

    @staticmethod  # 함수 재정의
    def backward(ctx, grad_output):
        """
        역전파 단계에서는 출력에 대한 손실의 변화도를 갖는 Tensor를 받고, 입력에
        대한 손실의 변화도를 계산합니다.
        """
        input, = ctx.saved_tensors  # forward에서 저장된 컨텍스트를 load
        grad_input = grad_output.clone()
        grad_input[input < 0] = 0
        return grad_input


dtype = torch.float
device = torch.device("cpu")
# device = torch.device("cuda:0") # GPU에서 실행하려면 이 주석을 제거하세요.

# N은 배치 크기이며, D_in은 입력의 차원입니다;
# H는 은닉층의 차원이며, D_out은 출력 차원입니다.
N, D_in, H, D_out = 64, 1000, 100, 10

# 입력과 출력을 저장하기 위해 무작위 값을 갖는 Tensor를 생성합니다.
x = torch.randn(N, D_in, device=device, dtype=dtype)
y = torch.randn(N, D_out, device=device, dtype=dtype)

# 가중치를 저장하기 위해 무작위 값을 갖는 Tensor를 생성합니다.
w1 = torch.randn(D_in, H, device=device, dtype=dtype, requires_grad=True)
w2 = torch.randn(H, D_out, device=device, dtype=dtype, requires_grad=True)

learning_rate = 1e-6
for t in range(500):
    # 사용자 정의 Function을 적용하기 위해 Function.apply 메소드를 사용합니다.
    # 여기에 'relu'라는 이름을 붙였습니다.
    relu = MyReLU.apply ## 적용된다?

    # 순전파 단계: Tensor 연산을 사용하여 예상되는 y 값을 계산합니다;
    # 사용자 정의 autograd 연산을 사용하여 ReLU를 계산합니다.
    y_pred = relu(x.mm(w1)).mm(w2) ## relu input변수로 들어간 후 계산되어 mm(w2) 수행

    # 손실을 계산하고 출력합니다.
    loss = (y_pred - y).pow(2).sum()
    if t % 100 == 99:
        print(t, loss.item())

    # autograde를 사용하여 역전파 단계를 계산합니다.
    loss.backward()  # backward()

    # 경사하강법(gradient descent)을 사용하여 가중치를 갱신합니다.
    with torch.no_grad():
        w1 -= learning_rate * w1.grad
        w2 -= learning_rate * w2.grad

        # 가중치 갱신 후에는 수동으로 변화도를 0으로 만듭니다.
        w1.grad.zero_()
        w2.grad.zero_()

99 889.4566040039062
199 24.183610916137695
299 0.9068278670310974
399 0.03599667549133301
499 0.0018360874382779002


## nn모듈

- PyTorch의 autograd 기능은 복잡한 연산자를 정의하고 유도해내는데 편하지만, 큰 뉴럴 네트워크에서는 구성하는데 어려움이 많다.

- TensorFlow에서는 이러한 어려움을 극복하기 위해 Keras, TensorFlow-Slim, TFLearn등을 사용한다.

- PyTorch에서는 동일한 기능을 위해 nn module를 구현하였다.

In [ ]:
# nn모듈
import torch

# N은 배치 크기이며, D_in은 입력의 차원입니다;
# H는 은닉층의 차원이며, D_out은 출력 차원입니다.
N, D_in, H, D_out = 64, 1000, 100, 10

# 입력과 출력을 저장하기 위해 무작위 값을 갖는 Tensor를 생성합니다.
x = torch.randn(N, D_in)
y = torch.randn(N, D_out)

# nn 패키지를 사용하여 모델을 순차적 계층(sequence of layers)으로 정의합니다.
# nn.Sequential은 다른 Module들을 포함하는 Module로, 그 Module들을 순차적으로
# 적용하여 출력을 생성합니다. 각각의 Linear Module은 선형 함수를 사용하여
# 입력으로부터 출력을 계산하고, 내부 Tensor에 가중치와 편향을 저장합니다.
model = torch.nn.Sequential(
    torch.nn.Linear(D_in, H),
    torch.nn.ReLU(),
    torch.nn.Linear(H, D_out),
)

# 또한 nn 패키지에는 널리 사용하는 손실 함수들에 대한 정의도 포함하고 있습니다;
# 여기에서는 평균 제곱 오차(MSE; Mean Squared Error)를 손실 함수로 사용하겠습니다.
loss_fn = torch.nn.MSELoss(reduction='sum')

learning_rate = 1e-4
for t in range(500):
    # 순전파 단계: 모델에 x를 전달하여 예상되는 y 값을 계산합니다. Module 객체는
    # __call__ 연산자를 덮어써(override) 함수처럼 호출할 수 있게 합니다.
    # 이렇게 함으로써 입력 데이터의 Tensor를 Module에 전달하여 출력 데이터의
    # Tensor를 생성합니다.
    y_pred = model(x)

    # 손실을 계산하고 출력합니다. 예측한 y와 정답인 y를 갖는 Tensor들을 전달하고,
    # 손실 함수는 손실 값을 갖는 Tensor를 반환합니다.
    loss = loss_fn(y_pred, y)
    if t % 100 == 99:
        print(t, loss.item())

    # 역전파 단계를 실행하기 전에 변화도를 0으로 만듭니다.
    model.zero_grad()

    # 역전파 단계: 모델의 학습 가능한 모든 매개변수에 대해 손실의 변화도를
    # 계산합니다. 내부적으로 각 Module의 매개변수는 requires_grad=True 일 때
    # Tensor 내에 저장되므로, 이 호출은 모든 모델의 모든 학습 가능한 매개변수의
    # 변화도를 계산하게 됩니다.
    loss.backward()

    # 경사하강법(gradient descent)를 사용하여 가중치를 갱신합니다. 각 매개변수는
    # Tensor이므로 이전에 했던 것과 같이 변화도에 접근할 수 있습니다.
    with torch.no_grad(): # torch.no_grad()를 사용하여 연산의 추적을 피한다.
        for param in model.parameters():
            param -= learning_rate * param.grad # 계산된 parameter들의 loss의 gradient에 learning_rate를 곱한 값을 현재의 가중치에서 빼줌으로 학습을 진행한다.